name: weave-action
author: weave.works
description: identify violations in your IaC files

inputs:
  path:
    description: path to resources kustomization
    required: true
    
  helm-values-file:
    description: path to helm values file
    required: false
  
  policy-path:
    description: path to policies kustomization
    required: true

  policy-helm-values-file:
    description: path to policies helm values file
    required: false

  # branch:
  #   description: branch name
  #   default: ${{ github.head_ref || github.ref }}
  #   required: false
  
  # commit:
  #   description: commit SHA
  #   default: ${{ github.event.pull_request.head.sha || github.sha }}
  #   required: false

  # token:
  #   description: github token
  #   default: ${{ github.token }}
  #   required: false

  sarif-file:
    description: export result in sarif format
    required: false
 
  sast-file:
    description: export result in sast format
    required: false
  
  json-file:
    description: export result in json format
    required: false

  remediate:
    description: auto remediate resources if possible
    required: false

  generate-git-report:
    description: auto remediate resources if possible
    default: "true"
    required: false

branding:
  color: blue
  icon: shield

runs:
  env:
    WEAVE_REPO_PROVIDER: github
    WEAVE_REPO_BRANCH: ${{ github.head_ref || github.ref }}
    WEAVE_REPO_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
    WEAVE_REPO_TOKEN: ${{ github.token }}


  using: docker
  image: docker://magalixcorp/weave-validator:dev
  args:
    - weave-validator
    - --path ${{ inputs.path }}
    - --helm-values-file ${{ inputs.helm-values-file }}
    - --policy-path ${{ inputs.policy-path }}
    - --policy-helm-values-file ${{ inputs.policy-helm-values-file }}
    # - --git-repo-provider github
    # - --git-repo-url ${{}}
    # - --git-repo-token ${{ inputs.token }}
    # - --git-repo-branch ${{ inputs.branch }}
    - --git-repo-sha ${{ inputs.commit }}
    - --sarif ${{ inputs.sarif-file }}
    - --sast ${{ inputs.sast-file }}
    - --json ${{ inputs.json-file }}
    - --remediate
    - --generate-git-report
